config/routes.rb
Rails.application.routes.draw do
  get 'lists/new'
  post 'lists' => 'lists#create'
  get 'lists/:id' => 'lists#show', as: 'list'
  get 'lists/edit'
  get '/' => 'homes#top'
  delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
    @lists = List.all
  end
  
  def create
    list = List.new(list_params)
    list.save
    redirect_to list_path(list.id)
  end

  def show
    @list = List.find(params[:id])  
  end

  def edit
  end
  
  def index
   
  end
  
  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to '/lists/new'
  end
  
  private
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</br>
</br>
印象を共有し交換することができます</p>

<%= link_to "start", "/lists/new" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/new.html.erb
<h1>Books</h1>

<% @lists.each do |list| %>
  <p>title</p>
    <span><%= list.title %></span>
  <p>body</p>
    <span><%= list.body %></span>
  
  <%= link_to "Show", list_path(list.id) %>
  <%= link_to "Destroy", destroy_list_path(list.id), method: :delete, "data-confirm" => "Are you sure?" %>
<% end %>

<h2>New book</h2>
<%= form_with model: @list, url: '/lists', method: :post do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Create Book' %>
<% end %>

app/views/lists/show.html.erb
<h2>Title</h2>
<p><%= @list.title %></p>

<h2>body</h2> 
<p><%= @list.body %></p>